// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5J0lrohM8q7aPmIPYjxCMaVNJO97VcBs',
    appId: '1:330558158098:web:736361efd505884fdeafcb',
    messagingSenderId: '330558158098',
    projectId: 'durio-ripeness-detector',
    authDomain: 'durio-ripeness-detector.firebaseapp.com',
    storageBucket: 'durio-ripeness-detector.appspot.com',
    measurementId: 'G-L7VEQYCX60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdZZuxjTWzfCOlfMVzIWApW09Nvhw7F2w',
    appId: '1:330558158098:android:36ce2cc7ffdadda8deafcb',
    messagingSenderId: '330558158098',
    projectId: 'durio-ripeness-detector',
    storageBucket: 'durio-ripeness-detector.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuFje5sBEf-SyxFPI5Kuwh4VqKbPv3D0Y',
    appId: '1:330558158098:ios:c9321df7c6c46905deafcb',
    messagingSenderId: '330558158098',
    projectId: 'durio-ripeness-detector',
    storageBucket: 'durio-ripeness-detector.appspot.com',
    iosBundleId: 'com.example.thesis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuFje5sBEf-SyxFPI5Kuwh4VqKbPv3D0Y',
    appId: '1:330558158098:ios:c9321df7c6c46905deafcb',
    messagingSenderId: '330558158098',
    projectId: 'durio-ripeness-detector',
    storageBucket: 'durio-ripeness-detector.appspot.com',
    iosBundleId: 'com.example.thesis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5J0lrohM8q7aPmIPYjxCMaVNJO97VcBs',
    appId: '1:330558158098:web:6693e2f6ec19d399deafcb',
    messagingSenderId: '330558158098',
    projectId: 'durio-ripeness-detector',
    authDomain: 'durio-ripeness-detector.firebaseapp.com',
    storageBucket: 'durio-ripeness-detector.appspot.com',
    measurementId: 'G-G5C69FSJWV',
  );
}
